# MARK: - catalogs
catalogs:
  x:
    '@oxc-node/cli': ^0.1.0
    'oxfmt': ^0.61.0
    'oxlint': ^1.76.0
    'oxlint-tsgolint': ^7.0.2001
    'typescript': npm:typescript-native-bridge@6.0.3-bridge.7.tsgo.7.0.2
  f:
    '@comark/svelte': ^0.6.2
    '@giscus/svelte': ^3.1.0
    '@iconify-json/ri': ^1.2.10
    '@vercel/analytics': ^2.0.1
    '@vercel/speed-insights': ^2.0.0
    '@sveltejs/adapter-auto': ^7.0.1
    '@sveltejs/kit': ^2.70.2
    'comark': ^0.6.2
    'comark-toml': ^0.1.2
    'rangi': ^2.2.0
    'svelte': ^5.56.8
    'svelte-check': ^4.7.4
    'svelte-themes': ^2.0.10
    'three': ^0.185.1
    'unocss': ^66.7.5
    'valibot': ^1.4.2
    'vite': ^8.1.5
  t:
    '@types/node': ^26.1.2
    '@types/three': ^0.185.1

# MARK: - supply chain
minimumReleaseAgeStrict: false
minimumReleaseAgeIgnoreMissingTime: false

# MARK: - dep opts
strictPeerDependencies: true
engineStrict: true
minimumReleaseAgeExclude:
  - comark-toml@0.1.2
