# MARK: - catalogs
catalogs:
  x:
    'oxfmt': ^0.61.0
    'oxlint': ^1.76.0
    'oxlint-tsgolint': ^7.0.2001
    'typescript': npm:typescript-native-bridge@6.0.3-bridge.7.tsgo.7.0.2
  f:
    '@sveltejs/adapter-auto': ^7.0.1
    '@sveltejs/kit': ^2.70.2
    'svelte': ^5.56.8
    'svelte-check': ^4.7.4
    'three': ^0.185.1
    'unocss': ^66.7.5
    'vite': ^8.1.5
  t:
    '@types/node': ^26.1.2

# MARK: - supply chain
minimumReleaseAgeStrict: false
minimumReleaseAgeIgnoreMissingTime: false

# MARK: - dep opts
strictPeerDependencies: true
engineStrict: true
