# MARK: - catalogs
catalogs:
  x:
    'oxfmt': ^0.58.0
    'oxlint': ^1.75.0
    'oxlint-tsgolint': ^0.24.0
    'typescript': ^6.0.3
  f:
    '@iconify-json/ri': ^1.2.10
    '@sveltejs/adapter-auto': ^7.0.1
    '@sveltejs/kit': ^2.70.1
    'svelte': ^5.56.7
    'svelte-check': ^4.7.3
    'unocss': ^66.7.5
    'vite': ^8.1.5
  t:
    '@types/node': ^26.1.1

# MARK: - supply chain
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false

# MARK: - dep opts
strictPeerDependencies: true
engineStrict: true
