export const WORDMARK_FADE_DURATION = 1080
export const WORDMARK_LIGHT_DELAY = 240
export const WORDMARK_BOOT_DURATION = 980
export const WORDMARK_BOOT_TOTAL_DURATION =
  WORDMARK_LIGHT_DELAY + WORDMARK_BOOT_DURATION
export const WORDMARK_CRASH_DURATION = 720
export const WORDMARK_CRASH_PIXEL_DURATION = 780
export const SKY_SCENE_START_DELAY = WORDMARK_FADE_DURATION - 160
