export const WORDMARK_BOOT_DURATION = 420
export const WORDMARK_BOOT_DELAY_STEP = 96
export const WORDMARK_BOOT_DELAY_VARIANTS = 17
export const WORDMARK_BOOT_TOTAL_DURATION =
  WORDMARK_BOOT_DURATION +
  WORDMARK_BOOT_DELAY_STEP * (WORDMARK_BOOT_DELAY_VARIANTS - 1)
export const SKY_SCENE_START_DELAY = WORDMARK_BOOT_TOTAL_DURATION - 360
