export const WORDMARK_FADE_DURATION = 1080
export const WORDMARK_LIGHT_DELAY = 240
export const WORDMARK_BOOT_DURATION = 980
export const WORDMARK_COOL_DURATION = 640
export const WORDMARK_CRASH_DURATION = 720
export const WORDMARK_CRASH_PIXEL_DURATION = 780
