export const WORDMARK_LIGHT_DELAY = 160
export const WORDMARK_BOOT_DURATION = 560
export const WORDMARK_COOL_DURATION = 180
export const WORDMARK_CRASH_DURATION = 720
export const WORDMARK_CRASH_PIXEL_DURATION = 780
